### ISSUE TITLE
How can i use `FeaturedPosts` component? It don't show in my page

### ISSUE THREAD

**Issue by alphawq** [z3by/vuepress-theme-modern-blog#7] opened 2020-03-20 08:48 UTC
Even though i set `featured: true` at post's `Frontmatter`, but it dose not work!
![image](https://user-images.githubusercontent.com/20399793/77148260-27175500-6aca-11ea-8eea-f5ace5a38dc5.png)

**Comment by z3by** [comment] 2020-03-20 11:00
you should see it in a slider in the home page like this one https://ahmadmostafa.com/

**Comment by z3by** [comment] 2020-03-20 11:00
Maybe because the post doesn't have an image so it is hard to see it.

**Comment by alphawq** [comment] 2020-03-20 11:22
> Maybe because the post doesn't have an image so it is hard to see it.

- **Adding image still doesn't work**
- **Console panel got the following error**
![image](https://user-images.githubusercontent.com/20399793/77159142-c266f500-6adf-11ea-8e6a-519101bb918a.png)
- **It should be that this component fails to render**
![image](https://user-images.githubusercontent.com/20399793/77159306-0e199e80-6ae0-11ea-9b39-dc4016edd155.png)

**Comment by z3by** [comment] 2020-03-20 11:51
How can I reproduce this error?

**Comment by alphawq** [comment] 2020-03-20 12:19
> How can I reproduce this error?

in my Blog repository, [here](https://github.com/alphawq/blog)

**Comment by z3by** [comment] 2020-03-20 12:35
I pulled your blog locally and set one post to featured and I can see it featured on the home page.

<img width="1286" alt="Screen Shot 2020-03-20 at 2 33 26 PM" src="https://user-images.githubusercontent.com/36268825/77163961-e7e00880-6ab7-11ea-9fb8-c8ed38b90bea.png">

**Comment by z3by** [comment] 2020-03-20 12:35
I am closing this issue, if you feel there is a problem with the actual theme please feel free to re-open it.

**Closed by z3by** 2020-03-20 12:35 UTC

**Comment by alphawq** [comment] 2020-03-20 12:44
**Thanks a lot!** 
I can run normally here too，😹！
May be a problem with my local environment...

**Comment by z3by** [comment] 2020-03-20 12:52
No problem! glad you figured it out! 🎉
